name: Debug-FLINT

on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check FLINT availability
        run: |
          apt search libflint
          sudo apt-get update
          sudo apt-get install -y libflint-dev
          pkg-config --modversion flint
          find /usr -name "flint.h" 2>/dev/null
          ldconfig -p | grep flint
